### ISSUE TITLE
Convert output data to web-audio playable data

### ISSUE THREAD

**Issue by e-radio-fk** [ConnorChristie/Audio-Mixer#10]
Hello, I am struggling with a problem and would really like some help!

I have a `Writable` stream as destination and I gather the mixed data by  implementing a custom `_write()` function.
My goal is to send this data to any connected client (browser based) and play them as audio using web-audio.

(The part where I send the data to the clients is working)

What I can't figure out is in what form to have the output data in order for them to be playable using web audio.

**Comment by timofriedlberlin** [comment]
@e-radio-fk maybe this helps you: https://stackoverflow.com/questions/8710846/play-pcm-data-by-webaudio-api

**Comment by e-radio-fk** [comment]
Thank you for the anwser! I managed to solve my problem by using [pcm-player](https://github.com/samirkumardas/pcm-player)
but this converstion (from 32bitFloat to 16bitInt) is definitely helpful in other places.
