### ISSUE TITLE
Use with discord.js

### ISSUE THREAD

**Issue by zRickz** [ConnorChristie/Audio-Mixer#8]
Can i use this library with discord.js voice receiver?

**Comment by Ziao** [comment]
For anyone arriving here later - yes, but you will have to pipe this through ffmpeg into an ogg opus format. I used it to successfully mix audio sources on the fly into a voice channel.

**Comment by e-radio-fk** [comment]
@Ziao Hi could you please share some code?

I am trying to convert the output stream data to ogg opus format aswell but I am struggling
